name: Slack Notifier if Website is down
description: 'Checks a website URL and alerts Slack if it is down'
inputs:
  website-url:
    description: 'The URL of the site to check. If multiple urls to be checked, separate them using comma.'
    required: true
  slack-webhook-url:
    description: 'The Slack Webhook URL where status change is to be posted'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Run Monitoring Script
      env:
        WEBSITE_URL: ${{ inputs.website-url }}
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
      run: python "${{ github.action_path }}/monitor.py"
      shell: bash

    - name: Upload state artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{github.workflow}}-state
        path: ${{github.workflow}}-state.json
